import "../components/handleStates.css";

export const metadata = {
  title: "Home App",
  description: "Generated by Next.js",
  keywords: "Next.js, React, JavaScript",
};

export default function Home() {
  return (
  <>
    <div className='center container'>
      <h1>Home</h1>
    </div>
  </>
  );
}