import Link from "next/link";

export const metadata = {
    title: "Tienda App",
    description: "Generated by Next.js",
    keywords: "Next.js, React, JavaScript",
};

export default function tiendaLayout({children}) {
    return (
        <nav>
            <h3>nav Tienda</h3>
            <ul>
                <li>
                    <Link href="/tienda">Tienda</Link>
                </li>
                <li>
                    <Link href="/tienda/categorias">Categorias</Link>
                </li>
            </ul>
        </nav>
    )
}