import "../../components/handleStates.css";

export const metadata = {
  title: "Login App",
  description: "Generated by Next.js",
  keywords: "Next.js, React, JavaScript",
};

export default function Login() {
  return (
  <>
    <div className='center container'>
      <h1>Login</h1>
    </div>
  </>
  );
}